name: text2image
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn
      - diffusers
      - transformers
      - torch
      - torchvision
      - numpy
      - pillow
      - python-multipart
